### ISSUE TITLE
Array out of bounds error - run_opf.f90

### ISSUE THREAD

**Issue by jjkas** [jtv3/oncvpsp#1]
Line 267 of run_opf.f90 has:

     phirn(:, ii - imin + 1 - iskip ) = aeuu(:) * sca
     phips(:, ii - imin + 1 - iskip ) = psuu(:)

Which causes failure for potassium input file when compiled with gfortran 8.4.1.

Replace with 
     phirn(1:irphs, ii - imin + 1 - iskip ) = aeuu(1:irphs) * sca
     phips(1:irphs, ii - imin + 1 - iskip ) = psuu(1:irphs)

assuming that irphs is always smaller than mmax (dimension of aeuu and psuu).

Input for K:
```
# ATOM AND REFERENCE CONFIGURATION
# atsym  z   nc   nv     iexc    psfile
K 19.00    3    3   -1012      upf
#
#   n    l    f        energy (Ha)
1    0    2.00
2    0    2.00
2    1    6.00
3    0    2.00
3    1    6.00
4    0    1.00
#
# PSEUDOPOTENTIAL AND OPTIMIZATION
# lmax
2
#
#   l,   rc,      ep,       ncon, nbas, qcut
0   1.35000  -1.29291    4    8   8.20000
1   1.45000  -0.69232    4    8   8.60000
2   1.60000   0.05000    4    8   8.20000
#
# LOCAL POTENTIAL
# lloc, lpopt,  rc(5),   dvloc0
4    5   1.10000      0.00000
#
# VANDERBILT-KLEINMAN-BYLANDER PROJECTORs
# l, nproj, debl
0    2   1.20369
1    2   0.80000
2    2   0.50000
#
# MODEL CORE CHARGE
# icmod, fcfact, rcfact
3   5.00000   1.40000
#
# LOG DERIVATIVE ANALYSIS
# epsh1, epsh2, depsh
-12.00   12.00    0.02
#
# OUTPUT GRID
# rlmax, drl
4.00    0.01
0
.true.
-1   1
```

**Comment by jtv3** [comment]
Thanks. Do you want to open a pull request (against the ocean branch) or just have me do it?

**Comment by jjkas** [comment]
I don't have  a forked version, so I thought it would be easier for you to do it. Unless you know of a way to make a pull request from a local repo.

**Comment by jtv3** [comment]
Should be fixed
